spring.application.name=BILLINGSYSTEM

spring.datasource.url=jdbc:mysql://localhost:3306/BillingSystem
spring.datasource.username=root
spring.datasource.password=182005kavi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true